# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jing's Blog
email: nj2408zjw@nj2408zjw.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer in iOS, c#, lua, php, try to be a full stacker...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jingwz.github.io" # the base hostname & protocol for your site
twitter_username: JingWZ
github_username:  JingWZ

# Build settings
markdown: kramdown
